---
title: "TEProf2_Heatmaps"
author: "Geno Guerra"
date: "2023-11-23"
output: html_document
---

```{r setup, include=FALSE}

# Process the data 

datafile = "/Users/gguerra/Library/CloudStorage/Box-Box/Francis _Lab_Share/TEProf2/S1_S10_S2_ProteinSequences_fragments_in_Human_herpes_proteins.blastp.e0.05.csv"

# Read in the datafile

df = read.csv(datafile, header=TRUE, sep = ",")


```

```{r functions, echo = FALSE}
quantile_breaks <- function(xs, n) {
  breaks <- quantile(as.matrix(xs), probs = seq(0, 1, length.out = n))
  breaks[!duplicated(breaks)]
}



```


Make sure install.packages("pheatmap") is run to install the necessary package. 

```{r heatmap setup, echo = FALSE, warning=FALSE}
library(pheatmap)  # RUN 

df0 =df#[which(df$GTEx_Total_without_Testis ==0),]
  uv=unique(df0$virus)
gaps =c()
# Need to reorder the data so that it is collected by group
ordered= c()
for(k in c(1:length(uv))){
  ordered = c(ordered,which(df0$virus ==uv[k]) )
  if(k!=length(uv)){
  gaps=c(gaps,length(ordered))
  }
}
df1 = df0[as.integer(ordered),]
row_groups = df1$virus
mat_row = data.frame(group=row_groups)
rownames(mat_row)= df1$protein
df2=(df1[,-c(1:2)])
row.names(df2)= df1$protein
mat_colors <- list(group = brewer.pal(length(unique(row_groups)), "Set3"))
names(mat_colors$group) <- unique(row_groups)

mgaps = c(0, gaps, nrow(df2))

#TCGA tumors only --------------------------
df3= df2[, grep("_tumor", colnames(df3))]
# -------------------------------------------

# Reorder rows so they are clustered within group. 
row.order = c()
for(i in c(1:(length(mgaps)-1))){
row.order = c(row.order, hclust(dist(df3[c((mgaps[i]+1):(mgaps[i+1])),]))$order + mgaps[i] )
}
df4 = df3[row.order,]

#df4= df3[, grep("_normal", colnames(df3))]

dfb = as.matrix(df4)
mat_breaks <- quantile_breaks(df4, 100)
# Alternative approach 
dfb=unlist(df4)
dfb=dfb[which(dfb >0)]
mat_breaks = seq(min(dfb), max(dfb), ceiling((max(dfb)-min(dfb))/10))
mat_breaks = c(0, mat_breaks)
colorpal= c("lightyellow", colorRampPalette(c("orange", "red", "darkred", "black"))(length(mat_breaks)-1))



pheat.plot=pheatmap(df4, cluster_rows = F, cluster_cols = T,annotation_row = mat_row,col=colorpal,show_colnames = TRUE , show_rownames = TRUE,gaps_row =gaps, annotation_colors =mat_colors, main = "", breaks=mat_breaks)
  

  

```
